"""add coach summaries

Revision ID: 911a58e93b68
Revises: 9fbea7b8e57b
Create Date: 2026-06-02 16:29:36.628336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '911a58e93b68'
down_revision: Union[str, Sequence[str], None] = '9fbea7b8e57b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coach_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('overall_summary', sa.Text(), nullable=False),
    sa.Column('primary_issue', sa.String(length=100), nullable=False),
    sa.Column('key_evidence', sa.Text(), nullable=False),
    sa.Column('practice_recommendation', sa.Text(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coach_summaries_id'), 'coach_summaries', ['id'], unique=False)
    op.create_index(op.f('ix_coach_summaries_match_id'), 'coach_summaries', ['match_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coach_summaries_match_id'), table_name='coach_summaries')
    op.drop_index(op.f('ix_coach_summaries_id'), table_name='coach_summaries')
    op.drop_table('coach_summaries')
    # ### end Alembic commands ###
